### ISSUE TITLE
Random exceptions thrown

### ISSUE THREAD

**Issue by shloooo** [altmp/altv-js-module-v2#256]
No resources are loaded with JSv2 and randomly the following error is logged: (There are maybe also others)

```
 [JSv2]   [JS] Exception caught while invoking event handler 
 [JSv2]   TypeError: Cannot read properties of null (reading 'type')
    at removeEntityFromAll (internal:shared/entity.js:64:41)
    at internal:shared/entity.js:54:5
    at Event.invoke (internal:shared/events.js:265:17)
    at onEvent (internal:shared/events.js:408:18)
```

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/f4a09e3a347e0d13d062143e5cb6b0f84111619f
